// Copyright (c) 2026 Jimmy Ma
// SPDX-License-Identifier: Elastic-2.0

package domain

// KnownActivities is the predefined list of activity types shown in the picker.
// Sourced from the Withings API workout category list.
// Users may also supply a custom value not in this list.
var KnownActivities = []string{
	"Badminton",
	"Baseball",
	"Basketball",
	"Bicycling",
	"BMX",
	"Bodyboard",
	"Bouldering",
	"Boxing",
	"Calisthenics",
	"Circuit Training",
	"Climbing",
	"CrossFit",
	"Dancing",
	"Elliptical",
	"Fencing",
	"Football",
	"Golf",
	"Gymnastics",
	"Handball",
	"HIIT",
	"Hiking",
	"Hockey",
	"Horse Riding",
	"Ice Hockey",
	"Ice Skating",
	"Indoor Cycling",
	"Indoor Running",
	"Kitesurfing",
	"Martial Arts",
	"Multi-Sport",
	"Pilates",
	"Rock Climbing",
	"Rowing",
	"Rugby",
	"Run",
	"Skating",
	"Skiing",
	"Snowboarding",
	"Soccer",
	"Sports Climbing",
	"Squash",
	"Stretching",
	"Surfing",
	"Swimming",
	"Table Tennis",
	"Tennis",
	"Volleyball",
	"Walk",
	"Water Polo",
	"Weightlifting",
	"Windsurfing",
	"Wrestling",
	"Yoga",
	"Zumba",
}
